### PR TITLE
Adding motor shields and robot misc blocks

### PR DESCRIPTION
**Pull request by EricSKennedy**
This update includes-
Creation of the robots category (zumo removed)
Addition of robots and robotmisc blocks and generators
English translations (not en-us)
The purpose is to provide a collection of motor shields from various manufacturers including one you can build yourself
The robots misc section is to provide blocks you might need for creating sumo robots
50% are tested.  I own two zumo bots and an ardumotor.  The rest should work since they were pulled from available specifications

Issues-
Haven't figured out how to get the reference to fourpin_range.jpg correct (robotmisc four pin ranger)
Can't figure out how to color the area to the left of the category (robots)- it is clear

### CODE REVIEW

**Comment by SebCanet** [comment]
thanks for this work ! And the internationalize way.
Why not creating a specific categorie for each product ? Zumobot, DFRobot, etc ?

**Comment by EricSKennedy** [comment]
Thanks for merging the commit!

Answers-
1 - We could create separate categories - I'd just rather have one general category with similar items.  It can be navigated in fewer clicks
2 - the picture is great - I just don't know how to get the reference right so it shows
3 - I'll fix the help URLs. The () were not needed on the version I made these for initially
4 - You can purchase the zumo as a kit.  When assembling it, a common mistake is to solder one of the motors backward.  If you do this, a program for driving your robot forward will actually make it turn.  I did this on one of the two zumobots I have.  Any blocks with &Speed, means the speed is adjustable.  Otherwise speed defaults in the code to 127 or medium speed.  Having adjustable speed makes the block more complicated, but helps you do things like account for one motor being a little stronger than the other.  With a speed adjustment it is easier to make a robot drive straight.

**Comment by SebCanet** [comment]
1. so we could do both, no problem to check for toolbox
2. put picture in /blocks/robot and write something like .appendField(new Blockly.FieldImage(Blockly.pathToBlockly + 'blocks/robot/servomoteur.jpg', 64, 64))
3.thanks
4.so maybe just a bloc 'counterwise TRUE or FALSE' ?

**Comment by EricSKennedy** [comment]
​4 - that might work.  I'll see what I can do.​

**Pull request merged**
